### ISSUE TITLE
Index Routes didn't work

### ISSUE THREAD

**Issue by abitwhy** [vecmat/vite-plugin-autorouter#6]
[Documents says](https://github.com/vecmat/vite-plugin-autorouter#index-routes) will transform `/index.vue` a `/` path, however it didn't.

![image](https://user-images.githubusercontent.com/68452982/158150304-275929d9-47d8-4271-a0ec-84c24dee35d1.png)

Although the [extendRoute](https://github.com/vecmat/vite-plugin-autorouter#extendroute) configuration can easily do this, i want to know if this is a bug?

The extendRoute configuration is followed, if someone needs:

```js
extendRoute(route) {
    const { path: defaultPath } = route
    const path = defaultPath.replace(/\/index$/, '')
    return { ...route, path }
},
```

**Comment by abitwhy** [comment]
By the way, what is the relationship between this repository and [vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages)?

**Comment by hanrea** [comment]
You can refer to this link : [index.vue](https://github.com/vecmat/vite-plugin-autorouter/blob/6975cc6842bb367b024742de1d90b860f1b5f92a/examples/vue-ssr/src/pages/index.vue#L11)


This package added block configuration support,See [example](https://github.com/vecmat/vite-plugin-autorouter/tree/main/examples)
